name: Release

on:
  push:
    branches:
      - master
      - releases/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1.1.0
        with:
          fetch-depth: 1
      - name: Use Node.js 12
        uses: actions/setup-node@v1.2.0
        with:
          node-version: 12
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Prepare release
        run: |
          mkdir -p release
          cp -r {.bin,build,LICENSE,README.md,package*.json} release
      - name: Upload release as artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: release
        env:
          CI: true
